default:
  ARCH:
    - COVER
    - T
    - X
    - D
    - S
    - LS
    - A
  STRUC: 
    - S
  MECH: 
    - M
  FIRE:
    - F
  MP: 
    - MP
  PLUMB: 
    - P
  ELEC: 
    - ES
    - E
  FIRE_SPRINK:
    - FS
default_w_civil:
  ARCH:
    - COVER
    - T
    - X
    - C
    - D
    - S
    - LS
    - A
  STRUC: 
    - S
  MECH: 
    - M
  FIRE:
    - F
  MP: 
    - MP
  PLUMB: 
    - P
  ELEC: 
    - ES
    - E
  FIRE_SPRINK:
    - FS
default_w_landscaping:
  ARCH:
    - COVER
    - T
    - X
    - D
    - S
    - LS
    - A
  STRUC: 
    - S
  MECH: 
    - M
  FIRE:
    - F
  MP: 
    - MP
  PLUMB: 
    - P
  ELEC: 
    - ES
    - E
  FIRE_SPRINK:
    - FS
default_w_LSC:
  ARCH:
    - COVER
    - T
    - X
    - D
    - S
    - LS
    - A
  STRUC: 
    - S
  MECH: 
    - M
  FIRE:
    - F
  MP: 
    - MP
  PLUMB: 
    - P
  ELEC: 
    - ES
    - E
  LSC:
    - LS-
  FIRE_SPRINK:
    - FS
